language: rust

cache: cargo

env:
  - RUSTFLAGS='-D warnings'

rust:
  - 1.33.0
  - stable
  - nightly

os:
  - linux
  - osx
  - windows

matrix:
  allowed_failures:
    - rust: nightly

script:
  - rustup component add clippy
  - cargo test --all --all-features
  - cargo test --all --all-features --release
  - cargo clippy

jobs:
  include:
    - stage: publish
      script: cargo publish --token "${CRATES_IO_TOKEN}"
      rust: stable
      if: (tag =~ ^v) AND (branch = master)

notifications:
  email:
    on_success: never
